### ISSUE TITLE
Error setting /newalert at 2.5% diff price 

### ISSUE THREAD

**Issue by AleksBuggato** [CryptoBuddyTeam/CryptoBuddyBot#4]
![img_20170811_232051](https://user-images.githubusercontent.com/30933793/29232507-3663be6c-7eec-11e7-81ee-5ed74511ed89.png)
When setting % diff price of preferred pair, the Bot add an alert at 3% (not as choosed 2.5%)

**Comment by atZeerg** [comment]
![image](https://user-images.githubusercontent.com/30902244/29244282-877e5938-7fb4-11e7-8223-5150def11a82.png)

all not int

**Comment by atZeerg** [comment]
Done, 
Problem with the var type assigned to db, it was int
