### ISSUE TITLE
[GUI Bug] Alert Message not formatted with schematic form

### ISSUE THREAD

**Issue by AleksBuggato** [CryptoBuddyTeam/CryptoBuddyBot#5]
![img_20170812_032316](https://user-images.githubusercontent.com/30933793/29236651-c9f49504-7f0d-11e7-9d21-6fc9c41ebc5b.png)

Replace with something like:
 
**Alert **
Arbitrage on SC_BTC -> 6.966%:
BUY Bittrex @ 0.00000234 BTC
SELL Hitbtc @ 0.00000250 BTC

**Comment by atZeerg** [comment]
![image](https://user-images.githubusercontent.com/30902244/29244427-f8d723e6-7fb7-11e7-97ed-052291751c8a.png)
Done
